### PR TITLE
Wait for first apply to complete before processing second

### PR DESCRIPTION
**Pull request by bwidawsk**
Not sure if this one is right...

### CODE REVIEW

**Comment by emersion** [comment]
If a configuration is being applied and e.g. a new head is plugged in (triggering another configuration to be applied), the first one will be cancelled by the compositor.

**Comment by bwidawsk** [comment]
I'll see if I can reproduce the issue after the next fix lands.

**Comment by emersion** [comment]
Hi, is this still an issue?

**Comment by bwidawsk** [comment]
Spam detection software, running on the system "zangief.bwidawsk.net",
has identified this incoming email as possible spam.  The original
message has been attached to this so you can view it or label
similar future email.  If you have any questions, see
root@localhost for details.

Content preview:  Nope On Aug 28, 2019 12:52 AM, Simon Ser <notifications@github.com>
   wrote: Hi, is this still an issue? 

Content analysis details:   (4.4 points, 4.1 required)

 pts rule name              description
---- ---------------------- --------------------------------------------------
-1.0 ALL_TRUSTED            Passed through trusted hosts only via SMTP
 0.0 HTML_MESSAGE           BODY: HTML included in message
 2.1 HTML_IMAGE_ONLY_12     BODY: HTML: images with 800-1200 bytes of
                            words
 0.1 MIME_HTML_ONLY         BODY: Message only has text/html MIME parts
 1.9 MISSING_MIMEOLE        Message has X-MSMail-Priority, but no X-MimeOLE
 0.4 HTML_MIME_NO_HTML_TAG  HTML-only message, but there is no HTML
                            tag
 1.0 T_REMOTE_IMAGE         Message contains an external image

The original message was not completely plain text, and may be unsafe to
open with some email clients; in particular, it may contain a virus,
or confirm that your address can receive spam.  If you wish to view
it, it may be safer to save it to a file and open it with an editor.

**Comment by bwidawsk** [comment]
I don't see it any more.

**Pull request closed without merging**
