### PR TITLE
Prefix all logs with [kanshi]

### PR DESCRIPTION
**Pull request by MisterDA**
I was debugging my Sway config and there were messages all over the place, it took me a while to figure out I had an error in the kanshi config. I thought that adding the `[kanshi]` prefix everywhere would help identify problems for next time.

### CODE REVIEW

**Comment by emersion** [comment]
I'd rather not do that. Maybe consider redirecting the output to a different file. Or use a tool to prepend a prefix to all lines.

**Comment by MisterDA** [comment]
Ok.
I've reordered the commits so that you may cherry-pick 7fd6460 if you want.
Guess I'll go with something like `exec sh -c "kanshi | sed s/^/[kanshi ]/"`.

**Comment by emersion** [comment]
> I've reordered the commits so that you may cherry-pick 7fd6460 if you want.

Ah, yes, pushed that commit, thanks.

**Comment by MisterDA** [comment]
Closing then.

**Pull request closed without merging**
